import { useEffect,useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

// getting for server side rendering
// export async function getServerSideProps(){
//   const resp = await fetch(`https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json`)
//   return {
//     props:{
//       pokemon: await resp.json()
//     }
//   }
// }


// static site generation
export async function getStaticProps(){
  const resp = await fetch(`https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json`)
  return {
    props:{
      pokemon: await resp.json()
    }
  }
}

export default function Home({pokemon}) {
  // client side rendering
  // const [pokemon,setPokemon] = useState([])
  //  useEffect(() => {
  //       async function getPokemon() {
  //       const resp = await fetch(`https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json`)
  //       setPokemon(await resp.json())
  //       }
  //       getPokemon()
        
  //   },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Pokemon List</h2>
      <div className={styles.grid}>
        {pokemon?.map((pokemon) => (
          <div className={styles.card} key={pokemon?.id}>
            <Link href={`/pokemon/${pokemon.id}`} legacyBehavior>
              <a>
                <img
                  src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon?.image}`}
                  alt={pokemon?.name}
                />
                <h3>{pokemon?.name}</h3>
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  )
}
